### ISSUE TITLE
No valid version available for homebridge-arlo-basestation

### ISSUE THREAD

**Issue by michaelkedwards** [eduardoboucas/homebridge-arlo-basestation#1]
Tried to install and got the following:

michaeledwards$ sudo npm install -g homebridge-arlo-basestation
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for homebridge-arlo-basestation

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michaeledwards/.npm/_logs/2018-10-26T05_31_59_512Z-debug.log

Maybe I'm the first to try and install and it isn't working. I have other plugins working and got an Carlo Pro2 cameras and would love to have a way to control the basestation. Appreciate your help.

**Comment by CooperCGN** [comment]
Same here, please help!

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-arlo-basestation' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose npm-session 25a18eaa648dbc89
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-arlo-basestation 1320ms (from cache)
8 silly fetchPackageMetaData error for homebridge-arlo-basestation@latest No valid versions available for homebridge-arlo-basestation
9 timing stage:rollbackFailedOptional Completed in 3ms
10 timing stage:runTopLevelLifecycles Completed in 1462ms
11 verbose type tag
12 verbose stack homebridge-arlo-basestation: No valid versions available for homebridge-arlo-basestation
12 verbose stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:36:11)
12 verbose stack     at fetchPackument.then.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:24:14)
12 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
12 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
12 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
12 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:694:18)
12 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
12 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
12 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
12 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
12 verbose stack     at runCallback (timers.js:705:18)
12 verbose stack     at tryOnImmediate (timers.js:676:5)
12 verbose stack     at processImmediate (timers.js:658:5)
13 verbose cwd /var/homebridgeArlo
14 verbose Linux 4.19.57-v7+
15 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-arlo-basestation"
16 verbose node v10.16.0
17 verbose npm  v6.9.0
18 error code ENOVERSIONS
19 error No valid versions available for homebridge-arlo-basestation
20 verbose exit [ 1, true ]
```
